version: '3.7'

services:

  sample:
    container_name: vue-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9528:9528
    environment:
      - CHOKIDAR_USEPOLLING=true